name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: "Publish"
    needs: [release]
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    uses: linc-technologies/.github/.github/workflows/ember_publish.yml@main
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
    with:
      node_version: '16.20'
      public: true
