name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{steps.release-please.outputs.releases_created}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          package-name: "@linc-technologies/ember-paper-password"
          release-type: "node"
          bootstrap-sha: "80dd68e536489b80855b0b638d675874f0f0b009"

  publish:
    name: "Publish"
    needs: [release]
    if: ${{needs.release.outputs.releases_created}}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml
